Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -21,7 +21,7 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
           GH_ORG: ${{ github.repository_owner }}
-          GH_NEW_INFRA_LIVE_REPO_NAME: "new-repo-1"
+          GH_NEW_INFRA_LIVE_REPO_NAME: ${{ inputs.repo_name }}
         run: |
           # Check if the repo exists before trying to create it
           GH_REPO_STATUS_CODE="$(curl --silent --write-out '%{http_code}' --output /dev/null \
@@ -59,7 +59,7 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
           GH_ORG: ${{ github.repository_owner }}
-          GH_NEW_INFRA_LIVE_REPO_NAME: "new-repo-1"
+          GH_NEW_INFRA_LIVE_REPO_NAME: ${{ inputs.repo_name }}
         run: |
           echo "Setting branch protection rules for $GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME. See https://docs.gruntwork.io/pipelines/security/branch-protection for more information on recommended rules."
           curl -L \
@@ -69,3 +69,39 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME/branches/main/protection \
             -d '{ "required_status_checks": { "strict": true, "checks": [ ] }, "required_pull_request_reviews": { "require_code_owner_reviews": true, "require_last_push_approval": true, "required_approving_review_count": 1 }, "enforce_admins": false, "restrictions": null }'
+      
+      - name: Add new repository to Gruntwork repo-allow-list
+        if: ${{ contains(inputs.terragrunt_command, 'apply') }}
+        id: update_repo_allow_list
+        env:
+          GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
+          GH_ORG: ${{ github.repository_owner }}
+          GH_NEW_INFRA_LIVE_REPO_NAME: ${{ inputs.repo_name }}
+        run: |
+          # Check if repo is already in repo-allow-list
+          REPO_IN_ALLOW_LIST="$(yq ".repo-allow-list | any_c(.  == \"$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME\")" .gruntwork/config.yml)"
+          if [[ "$REPO_IN_ALLOW_LIST" == "false" ]]; then
+            echo "Adding $GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME to repo-allow-list."
+            yq ".repo-allow-list += \"$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME\"" -i .gruntwork/config.yml
+            echo "create_pr=true" >> $GITHUB_OUTPUT
+          elif [[ "$REPO_IN_ALLOW_LIST" == "true" ]]; then
+            echo "Repo $GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME already exists in repo-allow-list. Skipping PR creation."
+            echo "create_pr=false" >> $GITHUB_OUTPUT
+          else
+            echo "Unspecified error. Exiting"
+            echo "create_pr=false" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+      - name: Create Pull Request to add the new repo to the allow list
+        if: ${{ steps.update_repo_allow_list.outputs.create_pr == 'true' }}
+        id: create_pr_allow_list
+        uses: peter-evans/create-pull-request@v5.0.2
+        with:
+          base: main
+          token: ${{ secrets.MANAGE_REPOS_TOKEN }}
+          add-paths: .gruntwork/config.yml
+          branch: "enhancement/sdlc-repo-${{ inputs.repo_name }}"
+          commit-message: "Add SDLC repo-allow-list permissions for ${{ github.repository_owner }}"
+          title: "Add SDLC repo-allow-list permissions for ${{ github.repository_owner }}"
+          body: |
+            This pull request updates the `config.yml` `repo-allow-list` permissions
